FILE_PATH: SSLSheets
FILE: Tacy_Foundation_SSL_Hours.xlsx
SHEET: Form Responses 1
CARROLL_SSL: SSLForms/carrollSSL.pdf
CHARLES_SSL: SSLForms/CESmithSSL.pdf
FREDERICK_SSL: SSLForms/frederickSSL.pdf
HOWARD_SSL: SSLForms/howardSSLsigned.pdf
MONTGOMERY_SSL: SSLForms/SignedMCPS.pdf
OLGC_SSL: SSLForms/OLGC_SSL.pdf
SSL_PATH: FilledSSL
LOGS_PATH: SSLEventLogs
SENDER: ssl.tacy@gmail.com